[package]
name = "taiko_preconf_avs_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.2", features = ["full", "node-bindings", "rlp"] }
alloy-rlp = "0.3"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
jsonrpsee = { version = "0.24", features = ["http-client", "server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
anyhow = "1.0.86"
k256 = "0.13"
ecdsa = "0.16"
elliptic-curve = "0.13"
reqwest = "0.12"
hex = "0.4"
tiny-keccak = "2.0"
secp256k1 = "0.29"
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "beacon-api-client" }
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "ethereum-consensus" }
ssz_rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "84ef2b71aa004f6767420badb42c902ad56b8b72" }
dotenv = "0.15"
rand_core = "0.6"
chrono = "0.4"
p2p-network = { path = "../p2pNode/p2pNetwork" }
bincode = "1.3"
serde_bytes = "0.11"
clap = "4.5"
futures-util = "0.3"
ethereum_ssz = "0.7"
ethereum_ssz_derive = "0.7"
bls_on_arkworks = "0.3.0"
num-bigint = "0.4.6"
rand = "0.8"

[dev-dependencies]
mockall_double = "0.3"
mockall = "0.13"
mockito = "1.4"
alloy-json-rpc = "0.2"

[features]
use_mock = []

# TODO: remove when the bug is fixed (https://github.com/ralexstokes/ssz-rs/issues/163)
[patch."https://github.com/ralexstokes/ssz-rs"]
ssz_rs = { git = "https://github.com/noahfigueras/ssz-rs", branch = "partial_merkle_tree" }
